
variables:
  DIST_DIR: dist/blood-bank-ng

stages:
  - build
  - deploy-prod
  - deploy-dev

build:
  stage: build
  image: node:latest
  script:
    - npm ci
    - npm run lint
    - npm run build-prod
  artifacts:
    paths:
      - dist/blood-bank-ng

deploy-prod:
  stage: deploy-prod
  only:
    - master
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -P 22020 -r -o StrictHostKeyChecking=no $DIST_DIR ubuntu@110.34.5.31:/var/www/blood-bank-client/html

deploy-dev:
  stage: deploy-dev
  only:
    - develop
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -P 22020 -r -o StrictHostKeyChecking=no $DIST_DIR ubuntu@110.34.5.31:/var/www/blood-bank-client-dev/html
