
variables:
  DIST_DIR: dist/blood-bank-ng/*
  DOC_DIR: documentation/*

stages:
  - build
  - generate-doc
  - deploy-dev
  - build-prod
  - deploy-prod

build:
  stage: build
  except:
    - master
  image: node:latest
  script:
    - npm ci
    - npm run lint
    - npm run build
  artifacts:
    paths:
      - dist/blood-bank-ng

build-prod:
  stage: build-prod
  only:
    - master
  image: node:latest
  script:
    - npm ci
    - npm run lint
    - npm run build-prod
  artifacts:
    paths:
      - dist/blood-bank-ng

generate-doc:
  stage: generate-doc
  only:
    - master
    - develop
  image: node:latest
  script:
    - npm run compodoc
  artifacts:
    paths:
      - documentation

deploy-prod:
  stage: deploy-prod
  only:
    - master
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -P 22020 -r -o StrictHostKeyChecking=no $DIST_DIR ubuntu@110.34.5.31:/var/www/blood-bank-client/html
    - scp -P 22020 -r -o StrictHostKeyChecking=no $DOC_DIR ubuntu@110.34.5.31:/var/www/blood-bank-client-doc/html

deploy-dev:
  stage: deploy-dev
  only:
    - develop
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -P 22020 -r -o StrictHostKeyChecking=no $DIST_DIR ubuntu@110.34.5.31:/var/www/blood-bank-client-dev/html
    - scp -P 22020 -r -o StrictHostKeyChecking=no $DOC_DIR ubuntu@110.34.5.31:/var/www/blood-bank-client-dev-doc/html
